# Generated by Django 4.2.4 on 2025-04-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255)),
                ('utilisateur', models.CharField(max_length=255)),
                ('mot_passe', models.CharField(max_length=255)),
                ('date_naiss', models.DateField(max_length=255)),
                ('matricule', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('matiere', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
