# Generated by Django 4.2.4 on 2025-04-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
