# Generated by Django 4.2.4 on 2025-04-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0002_enseignant_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
    ]
