# Generated by Django 4.2.4 on 2025-04-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0003_alter_enseignant_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='niveau',
            field=models.CharField(choices=[('Niveau-1', 'Niveau-1'), ('Niveau-2', 'Niveau-2'), ('Niveau-3', 'Niveau-3'), ('Niveau-4', 'Niveau-4'), ('Niveau-5', 'Niveau-5'), ('Niveau-6', 'Niveau-6')], default=1, max_length=50, verbose_name='Niveau'),
            preserve_default=False,
        ),
    ]
