# Generated by Django 4.2.4 on 2025-04-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=100, verbose_name='Nom de la Classe')),
                ('niveau', models.CharField(choices=[('Niveau-1', 'Niveau-1'), ('Niveau-2', 'Niveau-2'), ('Niveau-3', 'Niveau-3'), ('Niveau-4', 'Niveau-4'), ('Niveau-5', 'Niveau-5'), ('Niveau-6', 'Niveau-6')], max_length=50, verbose_name='Niveau')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='Notes.classe')),
            ],
        ),
    ]
