# Generated by Django 4.2.4 on 2025-04-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='classe',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='Notes.classe'),
        ),
    ]
