# Generated by Django 4.2.4 on 2025-04-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_etudiant_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau',
        ),
    ]
